name: Sync Project Documentation

on:
  workflow_dispatch:
  push:
    branches: ['1.20.1/create6']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Copy documentation to gh-pages and Commit
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

          git fetch origin
          git checkout origin/1.20.1/create6 -- src/main/resources/assets/oc2rcreate/doc/en_us/
          
          rsync -a src/main/resources/assets/oc2rcreate/doc/en_us/ ./. --remove-source-files
          cp -f ./create.md ./index.md
          rm ./create.md
          
          git add .
          git commit -m "Documentation Sync"
          git push
